### ISSUE TITLE
Clips sometime longer than expected

### ISSUE THREAD

**Issue by doesn123** [Sagnac/streamsave#8]
Sometimes the extracted clip will contain around 6 seconds more of video then expected (but for these extra seconds there is no audio). This also can happen before the expected starting time of the clip (each time this has happened it's been including audio).

I'm using mp4 local video and I'm using A-B Loops to determine the length of the extract.
Sorry if this is all rather vague, but I can't quite figure out a pattern.

**Comment by Sagnac** [comment]
Sometimes the clip points will differ from the chosen loop points because what's actually extracted is done so at keyframes so if you choose loop points which are far from one of these keyframes you will get a clip with a slightly different length (in your case it seems there's a difference of about 3 seconds on average from the start and end points).

I believe this is also the case if you use ffmpeg to cut the video without encoding using the `-ss`, `-t`, and `-c copy` switches as it likewise depends on keyframes, but you can compare and see if that's more accurate.

You can also use the `Alt+x` keybind to align the points before writing out the cache. In this case you should see a shift in the chosen length of about 6 seconds for the same video and segment you're referring to and the extracted clip should then match the new adjusted points.

Also you're using `cache=yes` for local videos, right?

**Comment by Sagnac** [comment]
Unfortunately this is simply a limitation of cutting streams without encoding, at least as far as I understand; from my experience ffmpeg will produce similar output if you simply copy the codecs because of the aforementioned keyframe requisite. If you need exact cuts you'll usually have to encode, I don't see an easy workaround for that.
